name: cst
version: '${project.version}'
main: org.cons0leweb.cst.main
api-version: '1.16'
commands:
  ctitle:
    description: Sends a custom title to the player with color and HEX code support.
    usage: /ctitle {player} {title};{subtitle} [fadeIn] [stay] [fadeOut]
    permission: cst.use
    permission-message: You do not have permission to use this command.
  cchat:
    description: Sends a custom chat message to the player with color, HEX code, clickable actions, and hover text support.
    usage: /cchat {player} {message} [action] [hoverText]
    permission: cst.use
    permission-message: You do not have permission to use this command.
  chelp:
    description: Displays help information for the cst plugin.
    usage: /chelp
    permission: cst.use
    permission-message: You do not have permission to use this command.
  cactionbar:
    description: Sends a custom message to the player's action bar with color and HEX code support.
    usage: /cactionbar {player} {message}
    permission: cst.use
    permission-message: You do not have permission to use this command.

permissions:
  cst.use:
    description: Allows the player to use the /ctitle, /cchat, /chelp, and /cactionbar commands.
    default: op